import { Product, Testimonial } from "./types";

// Note: These image paths are directly generated by the system inside our workspace
const HERO_IMAGE = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Balogun_Market%2C_Lagos_Island.jpg/1280px-Balogun_Market%2C_Lagos_Island.jpg";
const CHAFING_DISH_IMAGE = "https://picsum.photos/seed/chafingdish/800/800";
const COOKING_POTS_IMAGE = "https://images.unsplash.com/photo-1506484381205-f7945653044d?auto=format&fit=crop&q=80&w=800&h=800";

export const BRAND_INFO = {
  name: "Rozay Kitchen",
  tagline: "Bringing Quality, Style, and Functionality to Every Kitchen.",
  location: "Idumota, Block N, shop 89,90,91,92 New Pepsi Building, Merciful line. Ebute-ero Market Gorodom, Lagos Island, 101001, Lagos",
  hours: {
    weekdays: "Monday – Saturday: 8:00 AM – 6:00 PM",
    sunday: "Sunday: Closed"
  },
  socials: {
    instagram: "https://www.instagram.com/rozay_kitchen_",
    tiktok: "https://www.tiktok.com/@rozaykitchen860"
  },
  hero: {
    headline: "Premium Kitchen Appliances & Catering Equipment in Lagos",
    subheadline: "Discover high-quality chafing dishes, cookware, cooking pots, catering tools, coolers, and kitchen appliances trusted by homes, restaurants, and hospitality businesses across Nigeria.",
    image: HERO_IMAGE
  },
  about: "Rozay Kitchen is a trusted destination for high-quality kitchen appliances, cookware, and catering equipment in Lagos, Nigeria. Conveniently located in Idumota, Block N, shop 89,90,91,92 New Pepsi Building, Merciful line. Ebute-ero Market Gorodom, Lagos Island, we have built a reputation for providing premium kitchen solutions at competitive prices.\n\nWe specialize in a wide range of products, including elegant chafing dishes, durable cooking pots, cookware, catering tools, coolers, and reliable kitchen electronics designed to meet the needs of homes, restaurants, caterers, hotels, and hospitality businesses.\n\nAt Rozay Kitchen, we believe that every kitchen deserves products that combine functionality, durability, and style. Our commitment to quality, affordability, and exceptional customer service has made us a preferred choice for customers seeking modern kitchen solutions.\n\nWhether you are equipping a new kitchen, upgrading your catering business, or searching for premium cookware, Rozay Kitchen is dedicated to helping you find the perfect products for your needs.",
  mission: "To provide high-quality kitchen appliances, cookware, and catering equipment that enhance cooking experiences while delivering outstanding value, reliability, and customer satisfaction.",
  vision: "To become Nigeria's leading supplier of premium kitchen appliances, cookware, and catering equipment by consistently offering exceptional products, innovative solutions, and world-class customer service."
};

export const CHOOSE_US_POINTS = [
  {
    title: "Premium Quality",
    description: "We carefully select products known for safety, durability, functionality, and superior culinary performance."
  },
  {
    title: "Affordable Prices",
    description: "Enjoy competitive market rates and direct wholesale prices without ever compromising on quality."
  },
  {
    title: "Trusted Reputation",
    description: "We are proud to have earned the trust of premium households, main caterers, major restaurants, and hospitality businesses across Lagos."
  },
  {
    title: "Excellent Customer Service",
    description: "Our knowledgeable on-site and remote team is always available to guide and assist you in selecting the right equipment."
  },
  {
    title: "Wide Product Selection",
    description: "From luxury chafing dishes and massive cookware sets to storage coolers and electronic appliances—we carry all kitchen essentials."
  }
];

export const CATEGORIES = [
  "All",
  "Luxury Chafing Dishes",
  "Premium Cooking Pots",
  "Cookware Sets",
  "Catering Equipment",
  "Coolers & Storage",
  "Kitchen Appliances",
  "Utensils & Accessories"
];

export const PRODUCTS_DATA: Product[] = [
  {
    id: "prod-1",
    name: "Rozay Royal Gold Chafing Dish",
    category: "Luxury Chafing Dishes",
    description: "A gorgeous double-pan roll-top food warmer with polished gold handles and hardware. Crafted in heavy-duty food-grade stainless steel to elevate wedding receptions and hotel setups.",
    image: CHAFING_DISH_IMAGE,
    features: ["Double pan compartment", "Roll-top hydraulic 180° opening", "Mirror-finish polished stainless steel", "Dual fuel gel burners"],
    priceRange: "₦110,000",
    price: 110000,
    discountPrice: 95000,
    stockStatus: "In Stock",
    rating: 4.9
  },
  {
    id: "prod-2",
    name: "Luxury Rose-Gold Cookware Set",
    category: "Cookware Sets",
    description: "A beautiful 12-piece professional non-stick pot set styled with premium copper & rose-gold color tones. Features dual-pour lips and ultra-durable silicon grip handles.",
    image: COOKING_POTS_IMAGE,
    features: ["Induction-compatible triple ply bottoms", "Scratch-resistant ceramic coating", "Thick tempered glass lids", "Includes premium utensils"],
    priceRange: "₦85,000",
    price: 85000,
    discountPrice: 78000,
    stockStatus: "High Demand",
    rating: 4.8
  },
  {
    id: "prod-3",
    name: "Stellar Round Glass-Top Chafing Dish",
    category: "Luxury Chafing Dishes",
    description: "A compact and luxurious circular buffet server. Incorporates a smart steam-escape hydraulic soft-closed glass lid allowing guest visibility.",
    image: CHAFING_DISH_IMAGE,
    features: ["6.8 Litre capacity dome pan", "Slow-close hydraulic hinge", "Elegant gold-finished legs", "Single burner attachment"],
    priceRange: "₦95,000",
    price: 95000,
    stockStatus: "In Stock",
    rating: 4.7
  },
  {
    id: "prod-4",
    name: "Granite Non-Stick Heavy Cooking Pot Set",
    category: "Premium Cooking Pots",
    description: "Extremely rugged 10-piece die-cast granite coating cooking pot collection of immense thickness, resisting high heat and burning.",
    image: COOKING_POTS_IMAGE,
    features: ["Eco-friendly free of PFOA/Lead", "Double-riveted cooler handles", "Excellent thermal retention", "Includes 5 size options"],
    priceRange: "₦120,000",
    price: 120000,
    discountPrice: 110000,
    stockStatus: "In Stock",
    rating: 4.9
  },
  {
    id: "prod-5",
    name: "Industrial 3-Ply Stainless Steel Stock Pot",
    category: "Premium Cooking Pots",
    description: "Commercial large-capacity heavy stock pot designed for boiling large batches of food, stews, and Jollof rice for restaurants and caterers.",
    image: COOKING_POTS_IMAGE,
    features: ["Massive 50L capacity", "Reinforced thick rims", "Triple-clad bottom sandwich layer", "Compatible with gas and charcoal"],
    priceRange: "₦65,000",
    price: 65000,
    stockStatus: "Low Stock",
    rating: 4.6
  },
  {
    id: "prod-6",
    name: "Commercial Food Warmer & Showcase",
    category: "Catering Equipment",
    description: "Three-tier electric glass hot food showcase featuring curved glass panels and precise temperature control. Perfect for quick display warmers.",
    image: "",
    features: ["Curved heat-resistant glass front", "Temperature control up to 85°C", "Internal warm LED lighting", "Stainless steel crumb trays"],
    priceRange: "₦140,000",
    price: 140000,
    stockStatus: "Low Stock",
    rating: 4.5
  },
  {
    id: "prod-7",
    name: "Deep-Insulation Event Cooler Box (50L)",
    category: "Coolers & Storage",
    description: "Rugged exterior portable party and storage cooler designed specifically to withstand harsh outdoor sun and hold temperature up to 72 hours.",
    image: "",
    features: ["Extra thick foam insulation", "Secure heavy-duty t-latches", "Molded handles and drainage plug", "Holds up to 80 beverage cans"],
    priceRange: "₦45,000",
    price: 45000,
    stockStatus: "In Stock",
    rating: 4.7
  },
  {
    id: "prod-8",
    name: "Heavy-Duty Commercial Countertop Blender",
    category: "Kitchen Appliances",
    description: "High-horsepower 2500W professional blender with high-velocity copper motor that effortlessly mashes tough peppers, beans for Moinmoin, and dry tubers.",
    image: "",
    features: ["Unbreakable 2.5L Tritan pitcher", "6 hardened steel wave-cutting blades", "Infinite variable speed dial", "Overheat circuit safety protection"],
    priceRange: "₦55,000",
    price: 55000,
    stockStatus: "High Demand",
    rating: 4.9
  },
  {
    id: "prod-9",
    name: "Double-Jug Premium Beverage Dispenser",
    category: "Catering Equipment",
    description: "Elegant dual crystal-glass beverage stand equipped with high-gloss leak-free metal spigots and internal steel ice cylinders.",
    image: "",
    features: ["2 x 5L clear glass decanters", "Center steel column for ice filling", "Polished wooden/metal stand", "Rustproof leak-proof flow taps"],
    priceRange: "₦50,000",
    price: 50000,
    stockStatus: "In Stock",
    rating: 4.8
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Mrs. Funmi Adebayo",
    role: "CEO & Executive Caterer, Adebayo Events",
    location: "Lekki, Lagos",
    feedback: "Rozay Kitchen is my absolute number-one supplier! Their gold-accented chafing dishes are of exceptional quality and they have been keeping my wedding buffet setups incredibly elegant and warm for years."
  },
  {
    id: "test-2",
    name: "Mr. Emeka Okafor",
    role: "Proprietor, Golden Spoon Restaurant Group",
    location: "Ikeja, Lagos",
    feedback: "We bought all our heavy-duty commercial kitchen mixers, pots, and commercial blenders here. The durability under extreme daily restaurant usage is outstanding, and the customer service was highly professional!"
  },
  {
    id: "test-3",
    name: "Amara Nwachukwu",
    role: "Food Blogger & Enthusiast Home Chef",
    location: "Surulere, Lagos",
    feedback: "I am totally in love with my luxury non-stick pot set! The copper rose-gold color matches my kitchen interior flawlessly. Food slides off beautifully, and it feels premium without breaking the bank."
  },
  {
    id: "test-4",
    name: "Alhaji Ibrahim Musa",
    role: "Director of Facilities, Eko Horizon Suites",
    location: "Victoria Island, Lagos",
    feedback: "When equipping our new buffet line, we came directly to Ebutero Market and located Rozay Kitchen. They supplied us with state-of-the-art hospitality equipment and trays. Wholesale pricing and swift Lagos delivery."
  }
];
